### ISSUE TITLE
Crashes when functions are given wrong number of (positional) arguments

### ISSUE THREAD

**Issue by pgdr** [Parquery/icontract#108]
The following case, where `f` is given one too many arguments, should give the _original error message_ `TypeError: f() takes 0 positional arguments but 1 was given`:

```python
import icontract


@icontract.require(lambda: True)
def f():
    pass


f(0)
```

Instead, icontract crashes with the following traceback:
```
Traceback (most recent call last):
  File "f.py", line 9, in <module>
    f(0)
  File "/data/envs/e37/lib/python3.7/site-packages/icontract/_checkers.py", line 281, in wrapper
    resolved_kwargs = _kwargs_from_call(param_names=param_names, kwdefaults=kwdefaults, args=args, kwargs=kwargs)
  File "/data/envs/e37/lib/python3.7/site-packages/icontract/_checkers.py", line 61, in _kwargs_from_call
    mapping[param_names[i]] = func_arg
IndexError: list index out of range
```

This makes it difficult to locate the actual position of the bug.

**Comment by mristin** [comment]
Hi @pgdr,
Thanks for the issue! I'll have a look at it when I'm back from holidays on May 7th.

**Comment by mristin** [comment]
Hi @pgdr ,
I'm looking into the issue right now.

**Comment by mristin** [comment]
@pgdr I fixed the issue by silently ignoring the unexpected arguments and letting the underlying decorated function panic when called.

Unfortunately, I could not find the way to erase the decorators from the stack (see https://stackoverflow.com/questions/44813333/how-can-i-elide-a-function-wrapper-from-the-traceback-in-python-3). Hence, for your given example, the traceback now looks like:

```
Traceback (most recent call last):
  File "f.py", line 11, in <module>
    f(0)
  File "/home/marko/workspace/pqryopen/icontract/icontract/_checkers.py", line 348, in wrapper
    result = func(*args, **kwargs)
TypeError: f() takes 0 positional arguments but 1 was given
```

I suppose this is the best we can do at the moment -- please let me know if you know how we can remove the decorators from the traceback.
