### ISSUE TITLE
mypy 0.750 --strict error

### ISSUE THREAD

**Issue by galen104** [Parquery/icontract#122]
I'm using icontract 2.0.6 and I have trouble with `mypy --strict`.

ps: sorry, I have cloned and tested the branch master and it works well.
Can you make a new version with those fixes? 
Thanks

**Comment by mristin** [comment]
Hi @galen104 ,
Thanks for reporting the issue. This has been fixed in the master branch (see the pull request #120 ). We will release a new minor version in a week or two (@radomsak could you please confirm?).

**Comment by radomsak** [comment]
Hi @galen104 

We are having some issues with Pypi which will be resolved soon. I will let you know as soon as the new version is released. 

Thank you for your patience!

**Comment by mristin** [comment]
Hi @galen104 ,
The issue should be fixed in the current version (2.0.7) which is now also available on Pypi. Please let us know if it works for you as expected.

**Comment by mristin** [comment]
Hi @Sasha93 
I think this issue can be closed now since it was resolved?
