### ISSUE TITLE
testing functions validated with icontract

### ISSUE THREAD

**Issue by ibeglab** [Parquery/icontract#123]
I have a simple function that use `icontract` validation:

```
@icontract.require(lambda filename: os.path.isfile(filename))
def row_count(filename: str) -> int:
    with open(filename, encoding='utf-8') as file:
        return sum(1 for _ in file)
```

I'm using pytest for testing, and I have the following issues:
- I cannot test the function because the contract will always fail
- If I pass `-O` during testing to disable the contracts, the coverage test still complains about the `icontract` line:

```
file_utils.py                     68     19     38     15    64%   16->exit, ..
```

16 is the  `icontract` line:

How can I do?
Is there a better way instead of adding everywhere `# pragma: no cover` and pass `-O`?

ps: for example can you add a simpler way to disable all contracts for example for testing purpose?

Thanks.

**Comment by mristin** [comment]
Hi @ibeglab ,
Have you looked at `enabled` argument (https://github.com/Parquery/icontract/blob/master/README.rst#toggling-contracts)?

Please help me understand better your use case: you have some contracts that pass in production, but fail in test? These are the tests that you would like to disable in test, but enable in production? 

On the other hand, there are other tests  that pass both in production and test and should be always enabled? 

Here are two approaches that come to my mind:

1) Pytest sets the environment variable `PYTEST_CURRENT_TEST` (https://docs.pytest.org/en/latest/example/simple.html#pytest-current-test-environment-variable). You could use it to enable/disable pytested contracts.

2) Alternatively, you could introduce a global variable `IN_TEST` in your module and set it to True in your test script. 

Would that work?

**Comment by ibeglab** [comment]
I have some contracts that prevent me to properly test functions. In the example above, I cannot test `row_count()` function for `FileNotFoundError` exception.
During the development helps me to have contracts that ensure those kind of things, but tests should not rely on contracts.

I have tried with `enabled=not bool(os.environ.get('PYTEST_CURRENT_TEST'))`.
In production the contract is active as expected, but it is also active during testing.
But a simple 

```
print(not bool(os.environ.get('PYTEST_CURRENT_TEST')))
```

inside a test routine in pytest give me `False`.
How can I properly disable contracts during testing?

**Comment by mristin** [comment]
Hi @ibeglab ,
I'll fire up pytest environment tonight and test it with icontract.
If you want to test it in the meanwhile, could you try:

```
@icontract.require(
  lambda filename: os.path.isfile(filename),
  enabled='PYTEST_CURRENT_TEST' not in os.environ)
def row_count(filename: str) -> int:
    with open(filename, encoding='utf-8') as file:
        return sum(1 for _ in file)
```
?

**Comment by ibeglab** [comment]
Unfortunately it doesn't work.

**Comment by mristin** [comment]
I have just created a virtual environment:
```
python3 -m venv venv
. venv/bin/activate
pip3 install pytest icontract
```

The problem in the snippet above is that `PYTEST_CURRENT_TEST` is not defined (at least not in my pytest version 5.3.2).

A possible workaround is to define your own environment variable, _e.g._ `UNDER_TEST`:
`somemodule.py`:
```python
#!/usr/bin/env python3

import os

import icontract


@icontract.require(
  lambda filename: os.path.isfile(filename),
  enabled='UNDER_TEST' not in os.environ)
def row_count(filename: str) -> int:
    return 42

def main():
    row_count("some_file.txt")

if __name__ == "__main__":
    main()
```

`test_somemodule.py`:
```python
#!/usr/bin/env python3
import somemodule

def test_row_count()->None:
    assert somemodule.row_count("some_filename.txt") == 42
```

Finally, you need to set the environment variable when executing pytest:
```bash
UNDER_TEST=1 pytest
```

Would this work for you?

**Comment by ibeglab** [comment]
Yes this works. I solved this way:

```
irequire = partial(icontract.require, enabled='UNDER_TEST' not in os.environ)

@irequire(lambda filename: os.path.isfile(filename))  # pragma: no cover
...
```

and setting the environment variable `UNDER_TEST=1`
Thanks.

**Comment by mristin** [comment]
@radomsak I think the issue can be closed?
