### ISSUE TITLE
Class invariant changes __dict__ unexpectedly

### ISSUE THREAD

**Issue by treiher** [Parquery/icontract#136]
Usually `__dict__` can be used to compare if two instances have equal attributes. Adding an class invariant falsifies a `__eq__` method which is based on this assumption:

```Python
from icontract import invariant  
  
  
@invariant(lambda self: all(" " not in n for n in self.parts))  
class ID:  
    def __init__(self, identifier: str) -> None:  
        self.parts = identifier.split(".")  
  
    def __eq__(self, other: object) -> bool:  
        if isinstance(other, self.__class__):  
            print(self.__dict__)  
            print(other.__dict__)  
            return self.__dict__ == other.__dict__  
        return NotImplemented   
  
  
print(ID("A") == ID("A"))
```

```Console
{'parts': ['A'], '__dbc_invariant_check_is_in_progress__': True}
{'parts': ['A']}
False
```

In the shown example it is of course quite simple to fix the issue. In my use case multiple classes are inherited from a base class containing such a `__eq__` method. Each inherited class contains different additional attributes. Adding a separate `__eq__` method for each class containing an invariant would be cumbersome.

**Comment by mristin** [comment]
Hi @treiher ,
Thanks for reporting! These are the edge cases I couldn't have possibly thought of, so this is much appreciated!

Let me have a look at the problem tonight or tomorrow in more depth.

**Comment by mristin** [comment]
Hi @treiher ,
This also revealed a bug in multithreading scenarios. I'll try to come with a fix tonight.

**Comment by mristin** [comment]
@Sasha93 could you please merge in #137 so that this issue is also fixed?

**Comment by treiher** [comment]
Thanks for fixing this issue. When do you plan to release a new version containing this fix?

**Comment by mristin** [comment]
Hi @treiher ,
Already released, see #138 .

**Comment by treiher** [comment]
Oh, you are right, on PyPI is already version 2.3.1. I only looked at the releases on GitHub where there is still only version 2.2.0. Thanks again!

**Comment by mristin** [comment]
@Sasha93 could you please also make pending releases on github?

**Comment by Sasha93** [comment]
Sorry, I had forgotten about it. Done this morning;)
