### ISSUE TITLE
Performance impact of contracts particularly high

### ISSUE THREAD

**Issue by treiher** [Parquery/icontract#142]
I expected a substantial performance impact by using contracts, but the impact of invariants is huge, even with the simplest predicate. This is especially true for the latest version.

### Evaluation

Here is a small test program I used to evaluate the performance:

```Python
from icontract import invariant

@invariant(lambda self: True)
class A:
    def __init__(self, identifier: str) -> None:
        self.parts = identifier.split(".")

class B:
    def __init__(self, identifier: str) -> None:
        self.parts = identifier.split(".")

if __name__ == "__main__":
    import timeit

    print(timeit.timeit("A('X.Y')", setup="from __main__ import A", number=10000000))
    print(timeit.timeit("B('X.Y')", setup="from __main__ import B", number=10000000))
```

#### icontract 2.3.2

36.290041845990345
2.4590219910023734

#### icontract 2.2.0
              
9.24365290501737
2.4601732709852513

#### dpcontracts 0.6.0

4.568975409987615
2.543887578009162

Just for comparison I run the same test with dpcontracts.

**Comment by mristin** [comment]
Hi @treiher ,
Thanks a lot for the benchmarks, I really appreciate your feedback!

Could you write and run a similar benchmark for precondition and postcondition so that we can make sure it's mainly the issue with the invariants?

**Comment by treiher** [comment]
The performance for preconditions and postconditions is even worse (measured with version 2.3.2):

#### precondition

52.331567853019806
2.548302870010957

#### postcondition

63.87691364099737
2.5593633920070715

**Comment by mristin** [comment]
Oh, wow, this shouldn't be. Thread local must be the source of it. Sorry, I should have benchmarked. Would you mind sending me the scripts for precondition and postcondition?

**Comment by treiher** [comment]
I just modified the script shown above by replacing the invariant by a require/ensure at `__init__`.

**Comment by mristin** [comment]
Thanks! I'll try to dig into it over the weekend.

**Comment by mristin** [comment]
Hi @treiher ,
Sorry, the weekend was too busy. I hope to find some time tomorrow night (Tuesday).

**Comment by mristin** [comment]
Hi @treiher , let's continue the discussion in the pull request #143 .
