### ISSUE TITLE
AttributeError in contract caused by method call in constructor

### ISSUE THREAD

**Issue by treiher** [Parquery/icontract#149]
When a method is called in the constructor, an `AttributeError` is raised in the contract. Here is a reproducer:

```Python
from icontract import invariant


@invariant(lambda self: all(" " not in part for part in self.parts))
class ID:
    def __init__(self, identifier: str) -> None:
        self.parts = identifier.split(self.separator())

    def separator(self) -> str:
        return "."


ID("A")
```

```Console
$ python test.py  
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    ID("A")
  File "/home/tr/.local/lib/python3.8/site-packages/icontract/_checkers.py", line 461, in wrapper
    result = func(*args, **kwargs)
  File "test.py", line 7, in __init__
    self.parts = identifier.split(self.separator)
  File "/home/tr/.local/lib/python3.8/site-packages/icontract/_checkers.py", line 498, in wrapper
    _assert_invariant(contract=contract, instance=instance)
  File "/home/tr/.local/lib/python3.8/site-packages/icontract/_checkers.py", line 162, in _assert_invariant
    check = contract.condition(self=instance)
  File "test.py", line 4, in <lambda>
    @invariant(lambda self: all(" " not in part for part in self.parts))
AttributeError: 'ID' object has no attribute 'parts'
```

The contract works correctly when `self.separator()` is replaced by a string literal.

### Versions

icontract  2.3.4
asttokens  2.0.4
Python  3.8.5

**Comment by mristin** [comment]
@treiher thanks for reporting! I'll have a look tonight or tomorrow.

**Comment by mristin** [comment]
Could you please double-check the logic for me: the invariant checks need to be turned off during the constructor, otherwise you get an error such as this one (the invariant is checked before the call to `separator()` from within the constructor)?

**Comment by treiher** [comment]
Sounds like a reasonable solution to this problem.

**Comment by mristin** [comment]
@treiher The pull request #151 is up. Could you please review the test case and make sure that it matches your code: https://github.com/Parquery/icontract/pull/151/files#diff-b20043f83aeed569e372b4f454dbff95R230? Thanks in advance!

**Comment by treiher** [comment]
The test case looks good to me.

**Comment by mristin** [comment]
Hi @treiher ,
I hope #151 fixes the issue. Please re-open the issue otherwise.

Could you please check if there are any more issues pending on your side after you try out the head of the master branch? Once you confirm there are no issues, I'd bump a patch version.

**Comment by treiher** [comment]
It works fine now. Thanks for fixing!

**Comment by mristin** [comment]
@treiher please don't forget to ping me when you are confident we can move forward with the patch version :)

**Comment by mristin** [comment]
Hi @treiher ,
If you agree, I'd publish a patch version tomorrow (Monday)?

**Comment by treiher** [comment]
Yes, that would make sense. I haven't encountered any problem since the fix.

**Comment by mristin** [comment]
@treiher the new patch version (2.3.5) has been just released.
