### ISSUE TITLE
Testing for contract violation produces PendingDeprecationWarning

### ISSUE THREAD

**Issue by nyraghu** [Parquery/icontract#160]
When a function call violates a contract, I get a `PendingDeprecationWarning` from `ast`.  I don't get the warning for a call that conforms to the contract.

Example file `test_foo.py`:
``` python
from icontract import ViolationError, require
from pytest import raises

@require(lambda x: x > 0)
def include(x: int) -> int:
    return x

def test_violation():
    with raises(ViolationError):
        include(0)

def test_conformance():
    assert include(1) == 1
```

``` bash
$ pytest -k 'violation'
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /tmp/foo
collected 2 items / 1 deselected / 1 selected                                  

test_foo.py .                                                            [100%]

=============================== warnings summary ===============================
test_foo.py::test_violation
  /nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/ast.py:363: PendingDeprecationWarning: visit_Num is deprecated; add visit_Constant
    return visitor(node)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================== 1 passed, 1 deselected, 1 warning in 0.06s ==================
```

``` bash
$ pytest -k 'conformance'
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /tmp/foo
collected 2 items / 1 deselected / 1 selected                                  

test_foo.py .                                                            [100%]

======================= 1 passed, 1 deselected in 0.04s ========================
```
Ref: https://github.com/Parquery/icontract/blob/fb072699c5d7963699b8893a0033762dc3b4f2a1/icontract/_recompute.py#L49

**Comment by mristin** [comment]
Thanks for reporting the issue, @nyraghu! I'll try to have a look tomorrow or day after tomorrow.

**Comment by nyraghu** [comment]
> Which Python version are you using?

Python 3.8.5, icontract 2.3.6.

**Comment by mristin** [comment]
Hi @nyraghu ,
I published a patch version to Pypi fixing the deprecation warnings (https://pypi.org/project/icontract/).

(If you haven't done so, may I kindly ask you to star the project on GitHub to give it visibility?)

**Comment by nyraghu** [comment]
> I published a patch version to Pypi fixing the deprecation warnings (https://pypi.org/project/icontract/).

Many thanks.  The example I gave doesn't produce the warning with version 2.3.7 of the package.

> (If you haven't done so, may I kindly ask you to star the project on GitHub to give it visibility?

Done.  Thank you for your work on this project.
