### ISSUE TITLE
Invariant on subclass of generic Mapping produces ValueError

### ISSUE THREAD

**Issue by nyraghu** [Parquery/icontract#167]
An `invariant` decorator on a subclass of a generic `typing.Mapping` class produces a `ValueError`.  Using Python 3.8.5 and icontract 2.3.7.

Example file `foo.py`:
``` python
from icontract import invariant
from typing import Dict, Iterator, Mapping

@invariant(lambda self: True)
class Foo(Mapping[str, int]):
    def __init__(self, table: Dict[str, int]) -> None:
        self._table = table

    def __getitem__(self, key: str) -> int:
        return self._table[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._table)

    def __len__(self) -> int:
        return len(self._table)

    def __str__(self) -> str:
        return f'{self.__class__.__name__}({self._table})'

print(Foo({'a': 1}))
```

```
$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 21, in <module>
    print(Foo({'a': 1}))
  File "/tmp/foo/test-env/lib/python3.8/site-packages/icontract/_checkers.py", line 487, in wrapper
    instance = _find_self(param_names=param_names, args=args, kwargs=kwargs)
  File "/tmp/foo/test-env/lib/python3.8/site-packages/icontract/_checkers.py", line 432, in _find_self
    instance_i = param_names.index("self")
ValueError: 'self' is not in list
```
Disabling asssertions removes the error:
```
$ python -O foo.py 
Foo({'a': 1})
```

**Comment by mristin** [comment]
Hi @nyraghu ,
Thanks for reporting the bug! This looks like a very peculiar issue. Please give me a couple of days to have a proper look at it.

**Comment by mristin** [comment]
Hi @nyraghu ,
I hope #168 fixed it (it was about the `__new__` dunder). Could you please check out the master branch and see if there are more bugs caused by icontract in your code base?

Otherwise, I'd release the next patch version in a week.

**Comment by nyraghu** [comment]
The example I gave now works with icontract from master, as does my code with a subclass of a generic `typing.Mapping` class.

Many thanks for speedily fixing the issues.

**Comment by mristin** [comment]
@nyraghu great, thanks! If there are no bugs in a week, I'll bump the patch version.
