### ISSUE TITLE
See also: Precisely

### ISSUE THREAD

**Issue by CrazyPython** [Parquery/icontract#199]
https://github.com/mwilliamson/python-precisely

**Comment by mristin** [comment]
Hi @CrazyPython,
Would you suggest integrating icontract with precisely? Or you had something else on your mind?

**Comment by CrazyPython** [comment]
Yes, if you agree that such an integration would make sense and provide substantial benefit. Would be happy to contribute.

**Comment by CrazyPython** [comment]
As of writing, I am not fully confident integration would be useful or beneficial, as I don't currently maintain a medium-size or large-size Python project that uses `icontract`.

**Comment by mristin** [comment]
Hi @CrazyPython ,
I'm closing the issue due to inactivity. Please re-open if there is a clear use case or example to test and discuss the new feature(s).
