### ISSUE TITLE
flake8-functions-names for icontract?

### ISSUE THREAD

**Issue by cleder** [Parquery/icontract#206]
https://github.com/Melevir/flake8-functions-names

An extension for flake8 that validates functions names, decomposition and conformity with annotations. The plugin also has some validations of deal contracts.

Maybe this could be useful for icontract as well? I.e. validate a name based on conformity with a contract?

**Comment by mristin** [comment]
Hi @cleder ,
I looked into the plugin you sent. There is one rule regarding the `deal.pure`. However, icontract provides only checkers for pre, postcondotions and invariants. Can you maybe tell me a bit more what kind of rule you had in mind?

**Comment by mristin** [comment]
Hi @cleder ,
Is it OK to close this issue?

**Comment by cleder** [comment]
Yes, I thought there could be a quick win here, sorry it is not
