### ISSUE TITLE
Invariant on a class changes the type of the class

### ISSUE THREAD

**Issue by ciresnave** [Parquery/icontract#224]
```
from icontract import invariant

class TestClass1():
    test_int: int = 1

reveal_type(TestClass1)
# Type[TestClass1]

@invariant(lambda self: self.test_int == 1)
class TestClass2():
    test_int: int = 1

reveal_type(TestClass2)
# type
```

**Comment by ciresnave** [comment]
This was originally brought to my attention by PyLance which didn't like me using the invariant wrapped class as a type hint for a field in a dataclass like so:

@dataclass
class TestClass3():
    test_class: TestClass1

PyLance complained that it expected a Class but received a type instead.

**Comment by ciresnave** [comment]
I should mention that although this is a discrepancy, the code still works.  It's just PyLance and other type checkers that may complain about the difference.

**Comment by mristin** [comment]
Hi @ciresnave ,
Thanks a lot for reporting this issue! This is very relevant as many people who use contracts also use type checkers.

I have just added a test with mypy (please see [this snippet in the pull request 226]). The output of mypy 0.910 looks correct to me. Could you please double-check?

Does your version of PyLance uses mypy or it has its own implementation of type inference? If you happen to use mypy, could we first try to reproduce and fix the issue for your version of mypy and then move on to PyLance afterwards?

[this snippet in the pull request 226]: https://github.com/Parquery/icontract/pull/226/files#diff-c73bbfe75b60b569d306faa3a08b0eccc551e10b828c9d4e70ef3fb4f9b99196R79

**Comment by ciresnave** [comment]
Interesting.  Mypy does indeed show the two as identical...but it doesn't show the type as such.  Instead, it shows the following:

```
invariant_type_change.py:9:13: note: Revealed type is "def () -> stock_trader.invariant_type_change.TestClass1"
invariant_type_change.py:18:13: note: Revealed type is "def () -> stock_trader.invariant_type_change.TestClass2"

```
Just out of curiosity I added code to print the types:
```
print(type(instance_of_TestClass1))
print(type(instance_of_TestClass2))

```
The results would appear to indicate this may be a PyLance issue:
```
<class '__main__.TestClass1'>
<class '__main__.TestClass2'>
```

Maybe this is an issue with PyLance.  Thoughts on anything else you would like me to check before I open an issue with PyLance?

**Comment by mristin** [comment]
@ciresnave thanks for the further investigation!

The current type annotations for `invariant` decorator are actually quite vague, so maybe PyLance is having a problem with that. I tried to make a fix in the pull request #227. Could you please check out https://github.com/Parquery/icontract/commit/bb1495384f31e9130fcb58b2f1e397b0f0396313 and see if the more precise type annotations work with PyLance?

**Comment by ciresnave** [comment]
Okay.  I will check that and get you the results ASAP.  Since I still feel this is also questionable behavior in PyLance, I have opened an issue with them as well.  In case you're curious what they find:

https://github.com/microsoft/pylance-release/issues/1667

**Comment by ciresnave** [comment]
It appears your pull request [#227](https://github.com/Parquery/icontract/pull/227) did indeed solve the problem.  Interesting.  PyLance now sees TestClass2 as Type[TestClass2] as it should.

**Comment by ciresnave** [comment]
It also appears this is a known issue in mypy (https://github.com/python/mypy/issues/3135) and has been for years.  Basically, mypy isn't checking some aspects of wrapped/decorated classes.  PyLance appears to be adhering more closely to the standard than mypy if I'm reading it right.

**Comment by mristin** [comment]
@ciresnave thanks for your feedback! I'll merge the PR and bump a patch version this Monday.

**Comment by mristin** [comment]
@ciresnave I've just released the patch version on PyPI which should have the issue fixed. Please feel free to re-open the issue if there are further problems.
