### ISSUE TITLE
"Soft" contracts

### ISSUE THREAD

**Issue by leshchenko1979** [Parquery/icontract#234]
This is a proposal to introduce new functionality, "soft contracts".

### Problem
Sometimes you want to track unwanted behaviour but instead of getting an exception, you want to log it. 

Say, your code is already in production and nothing fatal happens when this unwanted behaviour occurs. You want to track and eliminate it, but if you use the usual contracts, the users would suffer - the execution will stop at the contract point with an exception. Thus trying to catch a minor unwanted behaviour via introducing a contract would cause a bigger problem.

So, you insert logging code into the body of your function. But now the code is less readable because of the "service code injections". The code would be cleaner if you used decorators similar to what `icontract` provides.

### Proposal
Introduce a set of decorators named `require_soft`, `ensure_soft`, `invariant_soft` that would log an error (or a warning?) in case the condition is breached, but keep on running.

This way the users are not harmed and the developer can track the bugs through inspecting the logs.

**Comment by leshchenko1979** [comment]
I've tried to build atop of the existing `icontracts` entities:
```python
from icontract import ViolationError, require

def require_soft(*contract_args, **contract_kwargs):
    def wrap(f):
        def check_log_run(*args, **kwargs):
            try:
                @require(*contract_args, **contract_kwargs)
                def check_run(*args, **kwargs):
                    return f(*args, **kwargs)

                return check_run(*args, **kwargs)

            except ViolationError:
                print("Contract failed")
                return f(*args, **kwargs)

        return check_log_run

    return wrap

@require_soft(lambda a: a > 5)
def check_a(a):
    print("Function executed")

print("Checking 3")
check_a(3)

print("Checking 6")
check_a(3)
```
But I'm getting the error message:
```
Exception has occurred: TypeError
File c:\Users\leshc\flipio\hermes\flipio_lib\soft_contracts.py, line 7 in check_log_run:
The argument(s) of the contract condition have not been set: ['a']. Does the original function define them? Did you supply them in the call?
  File "C:\Users\leshc\flipio\hermes\flipio_lib\soft_contracts.py", line 11, in check_log_run
    return check_run(*args, **kwargs)
  File "C:\Users\leshc\flipio\hermes\flipio_lib\soft_contracts.py", line 26, in <module>
    check_a(3)
```

**Comment by mristin** [comment]
Hi @leshchenko1979 <https://github.com/leshchenko1979>,
Thanks for your suggestion! It's always interesting to see how users have
different use cases! :-)

I'd suggest a smaller change: there is already an argument `error` where a
callback function can be supplied. In case the callback function returns
None, the error is simply not raised (but you can log it, of course). What
do you think?

**Comment by leshchenko1979** [comment]
Nice idea!

Sure it's better to make a smaller change!

So, I'm trying to figure out how it would look for the developer:
```python
from icontract import require
from logging import getLogger

logger = getLogger(__name__)

def log(x):
    logger.error("There has been an error with %s", x)
    return None

@require(lambda x: x > 5, error=log(x))
def func(x):
    ...
```

Is this what you had in mind?

If so, then the logging will be very bleak as we will lose the rich description of the contract violation generated by `icontract`. Is there a  way to log the standard violation description (containing the values of the variables checked etc.) as well?

**Comment by mristin** [comment]
@leshchenko1979 Please apologize first for the long delays. I've got a lot of work till about mid-December.

> Is this what you had in mind?
> If so, then the logging will be very bleak as we will lose the rich description of the contract violation [...]

You are correct. It would be indeed cool to preserve the full error message, but just log it instead of raising. Theoretically, you could write a decorator that catches the exceptions, but if I understand you correctly, you would like to execute the function *even though* the preconditions are violated?

**Comment by leshchenko1979** [comment]
Exactly. Log the exception and go on - that's the idea of "soft".

**Comment by mristin** [comment]
@leshchenko1979 one more thought. I am a bit reluctant to introduce three new decorators as that would duplicate a lot of code finally making the package unmaintainable. What do you think about supplying a special class, `Action`, to the `error` argument.

The logic would follow the cases with the errors, but just before raising, icontract would check whether the exception is an instance of `icontract.Action` and call its pre-defined abstract method `execute()` _instead of_ raising.

If you don't want to bother with the message and just use the one generated by icontract, you'd supply:

```
class MyAction(icontract.Action):
    ...

@icontract.require(..., error=MyAction)
```

(Please see the section [Custom Errors] in the docs for more information.)

Mind that the performance would be an issue, though, if you would abuse this construct for _frequent_ logging. In cases where you only occasionally log, this approach should work just fine. The downside with this approach is that you can not simply in-line the logging action and you have to wrap it into a separate class.

What do you think, how does that fit your particular use case?

[Custom Errors]: https://icontract.readthedocs.io/en/latest/usage.html#custom-errors

**Comment by leshchenko1979** [comment]
OK, we are dropping the idea of introducing additional decorators. Seems completely logical.

And I think your suggestion of a separate class with an `execute` method would also work.

However, I think there is a solution less bulky than adding a whole class, and it solves the task of supplying the user with the error message.

What if we go back to your original idea of checking the returned value of a callable passed as custom error, but provide to an additional argument `error_message` to it? This message argument would contain the detailed error message you typically raise an exception with.

Then, inside the callable, I would log the `error_message` and return `None` to you so that you know that no exception should be raised.

The usage could look like this:
```python
from icontract import require
from logging import getLogger

log = lambda error_message: getLogger(__name__).error(error_message)

@require(lambda x: x > 5, error=log)
def func(x):
    ...
```
How does this look to you?

**Comment by mristin** [comment]
@leshchenko1979 OK, I think we converged :). 

* I'll rename the argument to the error callback `_ERROR_MESSAGE` to keep the consistency with _ARGS and _KWARGS. 
* Whenever the error callback returns `None`, no error will be raised. In case of preconditions and invariants the decorated function will be executed despite the violation.

Please have patience with this feature. I won't be able to work on it till after the Christmas.

**Comment by leshchenko1979** [comment]
No problem, thanks!

**Comment by leshchenko1979** [comment]
Just an afterthought - is it possible that there is an already existing code base where people use `icontract` with the error parameter returning `None`?

In that case, our proposal would introduce some breaking changes to that code base and we better switch from `None` to some specialized class (eg, `DontRaiseOnViolation`).

**Comment by mristin** [comment]
@leshchenko1979 this would have raised an exception, so there should be no
problems with the existing clients.

**Comment by mristin** [comment]
Hi @leshchenko1979,
Just a heartbeat signal -- I haven't forgotten about the proposal. Unfortunately, I am still too involved in an intensive phase of a project that I hoped would be finished before Christmas. Please have patience, I hope to be able to have a look at it in January-February. 

I suppose this feature is not critical for your code base?

**Comment by leshchenko1979** [comment]
@mristin Marko, no worries at all! Of course it's not critical! Happy new year!

**Comment by mristin** [comment]
Hi @leshchenko1979 ,
I finally found time to look at this issue. Please apologize such a long delay.

There is a blocker that I was not aware of until I looked deeper in the code. Namely, when we deal with inheritance we can *weaken* the pre-conditions. It is OK if a pre-condition group of an ancestor is violated -- at least one group needs to be satisfied and then the function can execute. 

See https://www.eiffel.org/doc/eiffel/ET-_Inheritance, "Inheritance and contracts" for an example.

(Please let me know if you want me to explain you the problem in more detail if this explanation was too short.)

However, if we introduce the "soft" errors, the errors will be reported even though there is actually no violation.  Even if we introduce a separate decorators (say, `require_soft`, `ensure_soft` *etc.*), I don't really see how such logging could play nice with the inheritance. Frankly, I don't see an elegant solution here *within* icontract.

What about creating a separate library? I could copy & paste the re-computation code and introduce logging decorators (`conditionally_log_before`, `conditionally_log_after`?) with an explicit statement in the documentation that the logging behavior is *not* inherited and should be only applied to functions and not to instance methods?

**Comment by leshchenko1979** [comment]
I tried to understand this inheritance and contracts concept, but this is too complicated for me. 😅 

So, no worries, let's close this issue - I'll use workarounds.

**Comment by mristin** [comment]
> I tried to understand this inheritance and contracts concept, but this is too complicated for me.

The topics are unfamiliar, but in essence they are not too complex. Ping me if you'd like more reading material.

> So, no worries, let's close this issue - I'll use workarounds.

Ok. Please feel free to re-open if the feature becomes critical.
