### ISSUE TITLE
Installation of tests as package/module

### ISSUE THREAD

**Issue by kklein** [Parquery/icontract#239]
Hi! 

I realized that when installing `icontract` via pypi, `tests_3_6`, `tests_3_7` and `tests_3_8` are installed as packages/modules in the users' global environment as well - alongside `icontract`. Is this intentional? If so, is it necessary?

**Comment by mristin** [comment]
@kklein thanks for reporting! No, that is a mistake in `setup.py`. I'll try to fix it tonight.

**Comment by kklein** [comment]
Perfect, thanks a lot!
