### ISSUE TITLE
Can you release a wheel?

### ISSUE THREAD

**Issue by matthewdeanmartin** [Parquery/icontract#250]
They are useful in environments where sdist is prohibited because setup.py can execute arbitrary code on install, where as wheels can only execute code on import + invocation. It is a typosquatting defense.

`python setup.py sdist bdist_wheel` and then uploading `dist/*` with twine would do it, although there are more ways to do it.

Right now there is just a tar.gz - https://pypi.org/project/icontract/#files

Thanks

**Comment by mristin** [comment]
@matthewdeanmartin thanks, I'll add wheels when I'm back from holidays (late August).

**Comment by mristin** [comment]
@matthewdeanmartin I made a new release, 2.6.2, which includes a wheel: https://files.pythonhosted.org/packages/d8/91/9756e7cf0b155e80bf9a62beffdd1dec4afce43cc6ab7f432f2267c62762/icontract-2.6.2-py3-none-any.whl. 

I'm closing the issue. Please re-open if something is wrong with the wheel or the content is not what you expected *etc.*
