### ISSUE TITLE
The `asyncio.gather` method only triggers the decorators to check the first item

### ISSUE THREAD

**Issue by mikelane** [Parquery/icontract#255]
# Overview
When using icontract.require and icontract.ensure (and maybe others that I haven't tested) with an async function and an async validator or a regular lambda, only the first coroutine in the gather is checked.

# Example Code

```python
import asyncio

import icontract

from random import randint
from typing import Union

from loguru import logger

async def is_between_0_and_100(value):
    sleep_time = randint(1, 3)
    logger.info('Function is_between_0_and_100 sleeping for {sleep_time}', sleep_time=sleep_time)
    await asyncio.sleep(sleep_time)
    return 0 <= value < 100


@icontract.require(lambda bar: is_between_0_and_100(bar), error=ValueError('bar must be between 0 and 100'))
@icontract.ensure(lambda result: result is True)
async def is_less_than_42(bar: Union[int, float]) -> bool:
    sleep_time = randint(1, 5)
    logger.info('Called with bar = {bar}. Sleeping for {s}s', bar=bar, s=sleep_time)
    await asyncio.sleep(sleep_time)
    logger.info('bar = {bar} Done sleeping', bar=bar)
    return bar < 42


async def main() -> None:
    result = await asyncio.gather(
        is_less_than_42(0),  # should be True and it is
        is_less_than_42(50.0),  # Should raise an icontract.ViolationError, but doesn't
        is_less_than_42(-1),  # Should raise a ValueError, but doesn't
        is_less_than_42(1000),  # Should raise a ValueError, but doesn't
    )

    print(f'{result = }')  # Should not print anything, prints [True, False, True, False]


asyncio.run(main())
```

# Expected Output
I would expect there to be either an iContract ViolationError or a ValueError depending on which of the methods with the violations finished first.

# Actual Output:

```shell
2023-01-17 16:02:53.557 | INFO     | __main__:is_between_0_and_100:12 - Function is_between_0_and_100 sleeping for 3
2023-01-17 16:02:53.557 | INFO     | __main__:is_less_than_42:21 - Called with bar = 50.0. Sleeping for 4s
2023-01-17 16:02:53.557 | INFO     | __main__:is_less_than_42:21 - Called with bar = -1. Sleeping for 2s
2023-01-17 16:02:53.557 | INFO     | __main__:is_less_than_42:21 - Called with bar = 1000. Sleeping for 2s
2023-01-17 16:02:55.558 | INFO     | __main__:is_less_than_42:23 - bar = -1 Done sleeping
2023-01-17 16:02:55.559 | INFO     | __main__:is_less_than_42:23 - bar = 1000 Done sleeping
2023-01-17 16:02:56.557 | INFO     | __main__:is_less_than_42:21 - Called with bar = 0. Sleeping for 4s
2023-01-17 16:02:57.558 | INFO     | __main__:is_less_than_42:23 - bar = 50.0 Done sleeping
2023-01-17 16:03:00.558 | INFO     | __main__:is_less_than_42:23 - bar = 0 Done sleeping
result = [True, False, True, False]
```

As you can see, there is only one time that the `is_between_0_and_100` method was called and that was for the first method in the gather.

# Note:
If I move the second function up above the first in the gather call, then I do end up with a ViolationError. Similarly, if I move the original 3rd or 4th method to the top, I get a ValueError.

**Comment by mristin** [comment]
@mikelane thanks for reporting this! I'll have a look at it this or next week.

**Comment by mristin** [comment]
@mikelane could you please test if the code on the master branch solves your issue?

Once you give me OK, I'll bump a patch version and release it.

**Comment by mikelane** [comment]
I'll try it out today!

**Comment by mikelane** [comment]
I'm so sorry that I wasn't able to get to this last week. I did try it out just now. As a sanity check, I installed `icontract` in python 3.11.1 by running `pip3 install git+https://github.com/Parquery/icontract.git@master`. Then I created a function where I tested all of the above preconditions and postconditions and added several others. They all worked flawlessly. Thank you!
