### ISSUE TITLE
[Question] comparison with zope .interface

### ISSUE THREAD

**Issue by simkimsia** [Parquery/icontract#261]
I really like the readme comparing why icontracts is better than similar existing libraries

I like to get opinions about this library as well https://pypi.org/project/zope.interface/

And how icontracts stacked up against it

**Comment by mristin** [comment]
Hi @simkimsia ,
I am not sure how feature complete `zope.interface` is. I haven't tested it out myself, but it seems to me that it does not implement inheritance of contracts correctly. Please note that I might be wrong here as I only skimmed the documentation.

They mention at https://zopeinterface.readthedocs.io/en/latest/README.html#interface-inheritance in the footnote 3 that:

> The goal is substitutability. An object that provides an extending interface should be substitutable for an object that provides the extended interface. In our example, an object that provides IBaz should be usable wherever an object that provides IBlat is expected.

Additionally, and this is only my subjective perception!, the library seems overly complex for something simple such as contract definitions. In my opinion, it is already difficult to convince people to use contracts in general. Zope.interface is quite complex to build up for very little benefit in my book, so it will be even harder to convince people to write contracts. Again, this is my very personal opinion, and I am sure that other people would weigh in the trade-off differently.

(I'll close the issue -- please feel free to re-open if you have further questions!)

**Comment by simkimsia** [comment]
> In my opinion, it is already difficult to convince people to use contracts in general.

Truer words have not been said in the area of contracts.

Hopefully, is less true in future.

Thank you
