### ISSUE TITLE
[Question] How useful is a hypothetical icontract-coverage library be?

### ISSUE THREAD

**Issue by simkimsia** [Parquery/icontract#263]
Sorry if this is the wrong place to ask. 

There's no Discussions tab, so I thought to ask here.

There's such a thing as [docstr-coverage](https://github.com/HunterMcGushion/docstr_coverage)

it basically measures how much of the code has docstr.

Like regular unit test coverage libraries, but it measures how much of the code has docstr.

I wonder if there's a similar need to have a icontract-coverage library?

I am new to design by code and discover icontract by chance. So I like to hear the maintainers' and contributors' thoughts

**Comment by mristin** [comment]
Hi @simkimsia,
I don't think it is overly important metric. A lot of functions actually do not have contracts by definition apart from the typing. 

Moreover, it is not clear to me what a contract coverage would be -- how do you define what contracts are missing? Theoretically, you could apply symbolic execution or fuzzing and discover missing contracts as soon as the fuzzer or solver discovers uncovered parts of the input space that raise an exception. That might make for an interesting research paper.

Right now, you can manually run tools such as [icontract-hypothesis](https://github.com/mristin/icontract-hypothesis) and [CrossHair](https://github.com/pschanely/CrossHair) and test if they randomly discover missing contracts.

(I'll close the issue, but please feel free to re-open if you have further questions.)
