### ISSUE TITLE
Add commit message style documentation 

### ISSUE THREAD

**Issue by simkimsia** [Parquery/icontract#270]
As I was working on the PR #262 , I realized that there's a consistent commit message style. 

I hope there's documentation on this ideally.

**Comment by mristin** [comment]
Hi @simkimsia ,
You are right, the dev docs are quite sparse: 
https://icontract.readthedocs.io/en/latest/development.html

Pleasefeel free to make a PR & add the style. This is the style we used so far:
* past tense in the subject & body,
* max. 50 characters subject,
* max. 72 characters line length in the body (multiple lines are ok),
* past tense in the body as well,
* separate commits for the releases where the important changes are highlighted.

**Comment by simkimsia** [comment]
Roger that

I'll do on a separate page

**Comment by mristin** [comment]
@simkimsia there are no open pull requests -- I would just like to check up on this issue -- do you plan to continue working on it?

**Comment by simkimsia** [comment]
Yes I will do this

Sorry for dropping the ball on this @mristin

**Comment by simkimsia** [comment]
@mristin I added a PR for this at #286 

Let me know if there's any issues.
