### ISSUE TITLE
Dropped 3.6 on patch version change while advertising semantic versioning

### ISSUE THREAD

**Issue by jruere** [Parquery/icontract#273]
A patch version bump should be backwards compatible, according to https://semver.org/.

Dropping 3.6 is not backwards compatible, IMO. :)

Could a 2.6.4 release restore 3.6, and a 3.0 release drop 3.6?

**Comment by jruere** [comment]
Maybe depending on `contextvars` could make 3.6 work.

**Comment by jruere** [comment]
Adding `contextvars` to dependencies, made it work again for me.

**Comment by mristin** [comment]
Hi @jruere ,
I couldn't manage to install Python 3.6 on my Ubuntu as it requires `libssl < 3`. This was the message from PPA:deadsnakes:

> Supported Ubuntu and Python Versions
> 
> - Ubuntu 20.04 (focal) Python3.5 - Python3.7, Python3.9 - Python3.11
> - Ubuntu 22.04 (jammy) Python3.7 - Python3.9, Python3.11
> - Note: Python2.7 (all), Python 3.8 (focal), Python 3.10 (jammy) are not provided by deadsnakes as upstream ubuntu provides those packages.
> 
> Why some packages aren't built:
> - Note: for focal, older python versions require libssl<1.1 so they are not currently built
> - Note: for jammy, older python versions requre libssl<3 so they are not currently built
> - If you need these, reach out to asottile to set up a private ppa
> 
> The packages may also work on other versions of Ubuntu or Debian, but that is not tested or supported.

Would you mind making a pull request? If it works for you, I'll simply integrate it into the icontract, and publish the next patch version.

I should be able to get grips on a Window machine where Python 3.6 still runs tomorrow to test it on my side as well.

**Comment by jruere** [comment]
Created https://github.com/Parquery/icontract/pull/274.

**Comment by mristin** [comment]
@jruere do you have any more changes in mind, or should I release the patch version?

**Comment by jruere** [comment]
No more changes! Please, release. :D

**Comment by jruere** [comment]
Works like a charm! Thank you very much!
