### ISSUE TITLE
Outdated deal & typeguard

### ISSUE THREAD

**Issue by Luis-Hebendanz** [Parquery/icontract#282]
The typeguard version used is two mayor versions behind. Which makes it difficult to package icontract for package managers because of package name collision. The deal version used is also 3 years outdated

**Comment by mristin** [comment]
@Luis-Hebendanz thanks for the signal! Is there a particular version I should pin the packages to?

We actually use typeguard and deal only for benchmarks. Would it be easier if I move them to `[benchmark]` dependencies in `setup.py`?

**Comment by Luis-Hebendanz** [comment]
@mristin ahh yes please, that would be quite nice! :-)

**Comment by mristin** [comment]
@Luis-Hebendanz actually, the dependencies `dev` are meant for *internal* development and should not be included in a package of a distribution.

Can you perhaps suggest a better name than `dev` and then exclude these dependencies completely in the distributions?

**Comment by Luis-Hebendanz** [comment]
@mristin Ah no we run the tests for the python packages to make sure it still works, but we only have the newest version of the packages available.

**Comment by mristin** [comment]
@Luis-Hebendanz As I noted in the commit message from #284:
> We have to update the versions so that distributions can package them
> with the latest dependencies. Originally, we thought that we can simply
> separate the benchmark dependencies in a separate group in `setup.py`,
> but it turned out that some of the tests actually did involve `deal` and
> `typeguard`.

Would the current solution work for you? Please see [setup.py](https://github.com/Parquery/icontract/pull/284/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7).

**Comment by Luis-Hebendanz** [comment]
@mristin Awesome yes! That would work.

**Comment by mristin** [comment]
@Luis-Hebendanz a new patch release should be up soon: https://github.com/Parquery/icontract/actions/runs/6919955516

Please let me know if the problem persists, or if there are further problems.
