### ISSUE TITLE
Invariant of a subclass applies to its base

### ISSUE THREAD

**Issue by verinov** [Parquery/icontract#295]
Invariants of subclasses affect their base classes, as well as sibling classes.

Here is a example to reproduce the problem:
```
from icontract import invariant

@invariant(lambda: True)
class Base:
    pass

@invariant(lambda: False)
class Derived(Base):
    pass

Base()  # ViolationError
```

By the way, thanks for the nice library!

**Comment by mristin** [comment]
@verinov thanks a lot for reporting! I'm amazed that I didn't have a test case to catch this. Patch version 2.7.1 coming this week, then :)

**Comment by verinov** [comment]
I looked a bit more into this. The same code fails on older versions as well. But it doesn't fail, when I make `Base` derive from `icontract.DBC`.
My actual code uses `DBC`, and it did break with 2.6.6 -> 2.7.0. I'll try to make an small example, with fails and uses `DBC`.

**Comment by mristin** [comment]
@verinov please see #296.

**Comment by verinov** [comment]
I crafted an example, which fails with `DBC`:
```
from icontract import DBC, invariant

class A(DBC):
    def f(self):
        pass

@invariant(lambda: True)
class B(A):
    pass

@invariant(lambda: False)
class C_false(B):
    pass

@invariant(lambda: True)
class C_true(B):
    pass

C_true().f()  # ViolationError
```
It works on 2.6.6, but not 2.7.0.

**Comment by mristin** [comment]
Thanks, @verinov ! I have to investigate a bit more.

**Comment by mristin** [comment]
One thing that I noticed: I see that I forgot to properly collapse the invariants for setters and methods in:
https://github.com/Parquery/icontract/blob/625e79715356e3bd0843ba8f6cc3f177c29d4f08/icontract/_metaclass.py#L25-L42

**Comment by mristin** [comment]
@verinov I will be able to look into this issue only this Friday.

**Comment by mristin** [comment]
@verinov Just to confirm: I could reproduce the issue on my side, and now I'm looking into the bug.

**Comment by mristin** [comment]
@verinov A new patch version, 2.7.1, in which the bug is fixed, should be now up on PyPI.

**Comment by conversy** [comment]
Hi,

I'm (still) having a similar problem:

``` 
@icontract.invariant(lambda self: True)
class A(icontract.DBC):
    def __init__(self):
        pass

@icontract.invariant(lambda self: self.x > 0)
class B(A):
    def __init__(self, x):
        super().__init__()
        self.x = x

b = b(2)
```

leads to :
```
Traceback (most recent call last):
  File "/Users/conversy/ens/prog1A/2025/local.py", line 39, in <module>
    b = B(2)
  File "/Users/conversy/ens/prog1A/.venv/lib/python3.13/site-packages/icontract/_checkers.py", line 1027, in wrapper
    result = func(*args, **kwargs)
  File "/Users/conversy/ens/prog1A/2025/local.py", line 34, in __init__
    super().__init__()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/conversy/ens/prog1A/.venv/lib/python3.13/site-packages/icontract/_checkers.py", line 1030, in wrapper
    _assert_invariant(contract=invariant, instance=instance)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/conversy/ens/prog1A/.venv/lib/python3.13/site-packages/icontract/_checkers.py", line 526, in _assert_invariant
    check = contract.condition(self=instance)
  File "/Users/conversy/ens/prog1A/2025/local.py", line 31, in <lambda>
    @icontract.invariant(lambda self: self.x > 0)
                                      ^^^^^^
AttributeError: 'B' object has no attribute 'x'
```

Note that if I comment the call to `super().__init__()`, no exception is raised...
