### ISSUE TITLE
Better library name

### ISSUE THREAD

**Issue by mristin** [Parquery/icontract#47]
I was not aware of Java icontract library. It would be great to find a better name to facilitate Internet searches and also to avoid unnecessary citations or reference errors.

What about: pcontract (for python contract)?

**Comment by mristin** [comment]
@AbeDillon thanks for your suggestions!

I find Locke problematic (he was a major investor in the English slave trade). But "vow" is short and quite clear -- the best candidate so far!

**Comment by CrazyPython** [comment]
````
@vow_requires()
@vow_ensures()
```

What about these names? Sorry, I’ve been a little busy and haven’t been able to do much Python recently. I enjoy the discussions we’ve had together and sincerely would like more, Marko.

**Comment by mristin** [comment]
Hi @CrazyPython ,
Good to read you again as well :smile: 

I thought about introducing an alias in icontract so that current users don't need to change, but new users might prefer a shorter alias. There would be the module `vow` and it would have the decorators:

```
vow.before (precondition)
vow.after (postcondition)
vow.always (invariant)
vow.capture (snapshot)
```

What do you think?

**Comment by crypdick** [comment]
@mristin I like that proposal

**Comment by mristin** [comment]
Hi @crypdick ,
I'm currently quite busy with https://github.com/mristin/python-by-contract-corpus -- how much priority would you put on this feature?

**Comment by crypdick** [comment]
@mristin low priority for my team. We already are using icontract. I do think that for future adoption, though, avoiding name collisions is good and that the before/after/always/capture is easier to think about.

**Comment by mristin** [comment]
I'll close the issue for now. There is so much work related to icontract-hypothesis and python-by-contract-corpus pending so that this change would be very hard to prioritize in the next months.
