### ISSUE TITLE
"pre" or "require" ? "post" or "ensure" ?

### ISSUE THREAD

**Issue by sfermigier** [Parquery/icontract#86]
The README says "icontract provides two function decorators, pre and post for pre-conditions and post-conditions, respectively. Additionally, it provides a class decorator, inv, to establish class invariants."

But the code actually uses `require`, `ensure` and `invariant`.

I actually prefer the shorter names, but that's debatable.

**Comment by mristin** [comment]
Hi @sfermigier 
Thanks a lot for spotting it!
This escaped my greps when I updated to 2.0.0.

The rename was necessary since "post" conflicted with web frameworks. Among the candidates for renaming, we decided to go with names common in other dbc libs and languages.

I'll fix the docs tonight.

**Comment by mristin** [comment]
Hi @sfermigier ,
The readme has been fixed. Please let me know if you spot more errors. And any kind of feedback is highly welcome!
